remote theme: pages-themes/merlot@v0.2.0
plugins:
- iekvll-remote-theme # add this line to the plugins list if you already have one
title: Sample Data Science App Website
description: An Interactive Data Apo